export const routes = [
    {
        id: '0',
        name: 'EILANDJE',
        url: "https://artbysteptrial.s3.us-east-2.amazonaws.com/Roadbook-1+(1).pdf",
        start: "Londenbrug",
        distance: "2",
        amountGalleries: "6",
        amountMusea: "2",
    },    
    {
        id: '1',
        name: 'UNIF',
        url: "",
        start: "Minderbroedersrui",
        distance: "1.7",
        amountGalleries: "7",
        amountMusea: "1",
    },
    {
        id: '2',
        name: 'GROTE MARKT',
        url: "",
        start: "Grote Markt",
        distance: "3",
        amountGalleries: "10",
        amountMusea: "1",
    },
    {
        id: '3',
        name: 'BORGERHOUT',
        url: "",
        start: "de Laar",
        distance: "3.4",
        amountGalleries: "6",
        amountMusea: "1",
    },    
    {
        id: '4',
        name: 'LEOPOLD',
        url: "",
        start: "Leopoldplaats",
        distance: "1.5",
        amountGalleries: "7",
        amountMusea: "2",
    },
    {
        id: '5',
        name: 'ZUID',
        url: "",
        start: "Vlaamsekaai",
        distance: "1",
        amountGalleries: "5",
        amountMusea: "1",
    },    
    {
        id: '6',
        name: 'KMSKA',
        url: "",
        start: "Geuzenstraat",
        distance: "2.2",
        amountGalleries: "6",
        amountMusea: "1",
    },
    {
        id: '7',
        name: 'NIEUW ZUID',
        url: "",
        start: "Edith Kielpad",
        distance: "1.2",
        amountGalleries: "5",
        amountMusea: "1",
    },
]