export const routes = [
    {
        id: '0',
        name: 'EILANDJE',
        url: "https://artbysteptrial.s3.us-east-2.amazonaws.com/roadbooks/eild/eild_fr.pdf",
        start: "Londenbrug",
        distance: "2",
        amountGalleries: "6",
        amountMusea: "2",
        galleries: [
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
        ],
        image: "https://artbysteptrial.s3.us-east-2.amazonaws.com/img/eilandje-img.JPG",
        desc: "test",
    },    
    {
        id: '1',
        name: 'UNIV',
        url: "https://artbysteptrial.s3.us-east-2.amazonaws.com/roadbooks/univ/univ_fr.pdf",
        start: "Minderbroedersrui",
        distance: "1.7",
        amountGalleries: "7",
        amountMusea: "1",
        galleries: [
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
        ],
        image: "https://artbysteptrial.s3.us-east-2.amazonaws.com/img/univ-img.JPG",
        desc: "",
    },
    {
        id: '2',
        name: 'GROTE MARKT',
        url: "https://artbysteptrial.s3.us-east-2.amazonaws.com/roadbooks/gm/gm_fr.pdf",
        start: "Grote Markt",
        distance: "3",
        amountGalleries: "10",
        amountMusea: "1",
        galleries: [
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },

        ],
        image: "https://artbysteptrial.s3.us-east-2.amazonaws.com/img/grotemarkt-img.JPG",
        desc: "",
    },
    {
        id: '3',
        name: 'BORGERHOUT',
        url: "https://artbysteptrial.s3.us-east-2.amazonaws.com/roadbooks/bg/bg_en.pdf",
        start: "de Laar",
        distance: "3.4",
        amountGalleries: "6",
        amountMusea: "1",
        galleries: [
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
        ],
        image: "https://artbysteptrial.s3.us-east-2.amazonaws.com/img/borgerhout-img.JPG",
        desc: "",
    },    
    {
        id: '4',
        name: 'LEOPOLD',
        url: "https://artbysteptrial.s3.us-east-2.amazonaws.com/roadbooks/lpd/lpd_fr.pdf",
        start: "Leopoldplaats",
        distance: "1.5",
        amountGalleries: "7",
        amountMusea: "2",
        galleries: [
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
        ],
        image: "https://artbysteptrial.s3.us-east-2.amazonaws.com/img/leopold-img.JPG",
        desc: "",
    },
    {
        id: '5',
        name: 'ZUID',
        url: "https://artbysteptrial.s3.us-east-2.amazonaws.com/roadbooks/zuid/zuid_fr.pdf",
        start: "Vlaamsekaai",
        distance: "1",
        amountGalleries: "5",
        amountMusea: "1",
        galleries: [
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
        ],
        image: "https://artbysteptrial.s3.us-east-2.amazonaws.com/img/zuid-img.JPG",
        desc: "",
    },    
    {
        id: '6',
        name: 'KMSKA',
        url: "https://artbysteptrial.s3.us-east-2.amazonaws.com/roadbooks/kmska/kmska_en.pdf",
        start: "Geuzenstraat",
        distance: "2.2",
        amountGalleries: "6",
        amountMusea: "1",
        galleries: [
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
        ],
        image: "https://artbysteptrial.s3.us-east-2.amazonaws.com/img/kmska-img.JPG",
        desc: "",
    },
    {
        id: '7',
        name: 'NIEUW ZUID',
        url: "",
        start: "Edith Kielpad",
        distance: "1.2",
        amountGalleries: "5",
        amountMusea: "1",
        galleries: [
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
            {
                name: "f",
                startTime: "",
                finishTime: "",
            },
        ],
        image: "https://artbysteptrial.s3.us-east-2.amazonaws.com/img/niewzuid-img.JPG",
        desc: "",
    },
]